language: python
python: "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq rubygems graphicsmagick poppler-utils openoffice.org openoffice.org-java-common
  - sudo gem install docsplit -q
install:
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg -q -t 3
script: bin/test
